//PPA id will generate like  this
//  1. PPA id will be generated by the system and will be unique for each user
// first a word PPA
// then another word MCC
// then the index number of the user 21213,13614
// the index number may have 4 numbers some times that time a leading 0 will be add in the front
// finally a PPA id will looks like PPA-MCC-03614

export const generatePPAID = (index, userCount) => {
  const formatedIndex = index.length === 4 ? `0${index}` : index;
  return `PPA-MCC-${formatedIndex}/${userCount + 1}`;
};
