//PPA id will generate like  this
//  1. PPA id will be generated by the system and will be unique for each user
// first a word PPA
// then the abbreviation of the country of the user like  USA, UK, IND, etc.
// then the index number of the user 21213,13614
// the index number may have 4 numbers some times that time a leading 0 will be add in the front
// finally a PPA id will looks like PPA-LK-03614

export const generatePPAID = (country, index) => {
  const abbreviation = country.abbreviation;
  const formatedIndex = index.length === 4 ? `0${index}` : index;
  return `PPA-${abbreviation}-${formatedIndex}`;
};
